import type { MetadataRoute } from "next";

const base = "https://www.cigarledger.co.uk";

export default function sitemap(): MetadataRoute.Sitemap {
  const routes = [
    "",
    "/about",
    "/cigars",
    "/cheap-cigars-uk",
    "/cheapest-cigars-uk",
    "/cheap-cuban-cigars-uk",
    "/budget-cigars-uk",
    "/cigar-price-comparison",
    "/compare-cigar-prices-uk",
    "/cuban-cigar-prices-uk",
    "/cuban-cigar-prices",
    "/best-cigars-under-10",
    "/best-cigars-under-15",
    "/best-cigars-under-20",
    "/cohiba-prices-uk",
    "/montecristo-prices-uk",
    "/partagas-prices-uk",
    "/davidoff-prices-uk",
    "/cohiba-robusto-price-uk",
    "/cohiba-siglo-ii-price-uk",
    "/cohiba-siglo-vi-price-uk",
    "/montecristo-no-2-price-uk",
    "/montecristo-no-4-price-uk",
    "/partagas-serie-d-no-4-price-uk",
    "/h-upmann-magnum-46-price-uk",
    "/romeo-y-julieta-short-churchill-price-uk",
    "/cigar-import-duty-uk",
    "/cigar-landed-cost-uk",
    "/importing-cigars-from-europe-to-uk",
    "/best-place-to-buy-cigars-uk",
    "/cheapest-place-to-buy-cigars-uk",
    "/buy-cigars-online-uk",
    "/uk-cigar-prices",
    "/cigar-price-checker-uk",
    "/cohiba-price-list-uk",
    "/montecristo-price-list-uk",
    "/partagas-price-list-uk",
    "/romeo-y-julieta-price-list-uk",
    "/h-upmann-price-list-uk",
    "/cohiba-behike-52-price-uk",
    "/cohiba-behike-56-price-uk",
    "/montecristo-edmundo-price-uk",
    "/partagas-shorts-price-uk",
    "/hoyo-epicure-no-2-price-uk",
    "/cheap-cigars",
    "/cheapest-cigars",
    "/best-cheap-cigars-uk",
    "/cheapest-cuban-cigars",
    "/cheapest-cuban-cigars-uk",
    "/cigar-deals-uk",
    "/cigar-discounts-uk",
    "/best-cigar-prices-uk",
  ];

  return routes.map((route) => ({
    url: `${base}${route}`,
    lastModified: new Date(),
  }));
}
